=== camenduru/ic-light-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "IC-Light is a project to manipulate the illumination of images.",
      "author": "Lvmin Zhang (Lyumin Zhang)",
      "description": "The name 'IC-Light' stands for 'Imposing Consistent Light' (we will briefly describe this at the end of this page). Currently, we release two types of models: text-conditioned relighting model and background-conditioned model. Both types take foreground images as inputs.",
      "code": "https://github.com/lllyasviel/IC-Light",
      "jupyter": "https://github.com/camenduru/IC-Light-jupyter",
      "post": "https://twitter.com/camenduru/status/1788393502289596557",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/ic-light.ipynb",
      "tags": [
        "Image to Image"
      ],
      "widget": "readme"
    },
    "input_fg": {
      "type": "string",
      "description": "Input Image URL",
      "widget": "textarea"
    },
    "prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "width": {
      "type": "integer",
      "description": "Width"
    },
    "height": {
      "type": "integer",
      "description": "Height"
    },
    "seed": {
      "type": "integer",
      "description": "Seed"
    },
    "steps": {
      "type": "integer",
      "description": "Steps"
    },
    "a_prompt": {
      "type": "string",
      "description": "Added Prompt",
      "widget": "textarea"
    },
    "n_prompt": {
      "type": "string",
      "description": "Negative prompt",
      "widget": "textarea"
    },
    "cfg": {
      "type": "integer",
      "description": "CFG"
    },
    "highres_scale": {
      "type": "number",
      "description": "Highres Scale"
    },
    "highres_denoise": {
      "type": "number",
      "description": "Highres Denoise"
    },
    "lowres_denoise": {
      "type": "number",
      "description": "Lowres Denoise"
    },
    "bg_source": {
      "type": "string",
      "widget": "select",
      "description": "Light Direction",
      "oneOf": [
        {
          "description": "LEFT",
          "enum": [
            "LEFT"
          ]
        },
        {
          "description": "RIGHT",
          "enum": [
            "RIGHT"
          ]
        },
        {
          "description": "TOP",
          "enum": [
            "TOP"
          ]
        },
        {
          "description": "BOTTOM",
          "enum": [
            "BOTTOM"
          ]
        }
      ],
      "default": "BOTTOM"
    },
    "example": {
      "type": "string",
      "image1": "https://fakeimg.pl/768x1152/282828/eae0d0/?text=input#.png",
      "image2": "https://hips.hearstapps.com/hmg-prod/images/scarlett-johansson-attends-the-premiere-of-illuminations-news-photo-1639390369.jpg",
      "image3": "https://fakeimg.pl/768x1152/282828/eae0d0/?text=output#.png",
      "image4": "https://files.catbox.moe/2y2hxb.png",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/ic-light-tost/model.json
{
  "input_fg": "https://hips.hearstapps.com/hmg-prod/images/scarlett-johansson-attends-the-premiere-of-illuminations-news-photo-1639390369.jpg",
  "prompt": "beautiful woman, detailed face, neon light, city",
  "width": 512,
  "height": 768,
  "seed": 14,
  "steps": 25,
  "a_prompt": "best quality",
  "n_prompt": "lowres, bad anatomy, bad hands, cropped, worst quality",
  "cfg": 2,
  "highres_scale": 1.5,
  "highres_denoise": 0.5,
  "lowres_denoise": 0.9,
  "bg_source": "BOTTOM"
}
